### ISSUE TITLE
Units - selection area

### ISSUE THREAD

**Issue by kziel445** [kziel445/BulbWars#5]
## Issue
Units should be controllable by mouse with selection area.

## TODO
- [ ] Make selection area
- [ ] Make selection of unit
- [ ] Control units after selection
